//==============================================================================
// Auto-generated by OmniGPU Code Generator -- DO NOT EDIT
// Source: gen\vulkan_api.json
// Generated: 2026-07-14T23:59:45.618515
//==============================================================================

#include "vk_intercept.h"
#include "vulkan_serializer.h"
#include "command_batch.h"
#include <vulkan/vulkan.h>
#include <fmt/core.h>
#include <spdlog/spdlog.h>
#include <atomic>
#include <unordered_map>

namespace omnigpu::intercept {

namespace {

// Global original function pointer table
std::unordered_map<std::string, void*> g_original_fns;
bool g_initialized = false;

// Global batch for command accumulation
batch::CommandBatch* g_batch = nullptr;

// Request ID counter
std::atomic<uint32_t> g_next_request_id{1};

uint32_t next_request_id() {
    return g_next_request_id.fetch_add(1, std::memory_order_relaxed);
}

} // anonymous namespace

// ---------------------------------------------------------------------------
// vkCreateInstance
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateInstance_hook(const VkInstanceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkInstance* pInstance) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateInstance");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pInstance));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateInstance,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(const VkInstanceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkInstance* pInstance)>(g_original_fns["vkCreateInstance"]);

    return original(pCreateInfo, pAllocator, pInstance);
}
// ---------------------------------------------------------------------------
// vkDestroyInstance
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyInstance_hook(VkInstance instance, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyInstance");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(instance));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyInstance,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkInstance instance, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyInstance"]);

    return original(instance, pAllocator);
}
// ---------------------------------------------------------------------------
// vkEnumeratePhysicalDevices
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkEnumeratePhysicalDevices_hook(VkInstance instance, uint32_t* pPhysicalDeviceCount, VkPhysicalDevice* pPhysicalDevices) {
    SPDLOG_TRACE("Intercepted: {}", "vkEnumeratePhysicalDevices");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(instance));
    ser.write_u32(pPhysicalDeviceCount ? *pPhysicalDeviceCount : 0);
    ser.write_handle(reinterpret_cast<uint64_t>(pPhysicalDevices));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkEnumeratePhysicalDevices,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkInstance instance, uint32_t* pPhysicalDeviceCount, VkPhysicalDevice* pPhysicalDevices)>(g_original_fns["vkEnumeratePhysicalDevices"]);

    return original(instance, pPhysicalDeviceCount, pPhysicalDevices);
}
// ---------------------------------------------------------------------------
// vkCreateDevice
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateDevice_hook(VkPhysicalDevice physicalDevice, const VkDeviceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDevice* pDevice) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateDevice");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(physicalDevice));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pDevice));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateDevice,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkPhysicalDevice physicalDevice, const VkDeviceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDevice* pDevice)>(g_original_fns["vkCreateDevice"]);

    return original(physicalDevice, pCreateInfo, pAllocator, pDevice);
}
// ---------------------------------------------------------------------------
// vkDestroyDevice
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyDevice_hook(VkDevice device, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyDevice");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyDevice,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyDevice"]);

    return original(device, pAllocator);
}
// ---------------------------------------------------------------------------
// vkGetDeviceQueue
// ---------------------------------------------------------------------------
void VKAPI_PTR vkGetDeviceQueue_hook(VkDevice device, uint32_t queueFamilyIndex, uint32_t queueIndex, VkQueue* pQueue) {
    SPDLOG_TRACE("Intercepted: {}", "vkGetDeviceQueue");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_u32(static_cast<uint32_t>(queueFamilyIndex));
    ser.write_u32(static_cast<uint32_t>(queueIndex));
    ser.write_handle(reinterpret_cast<uint64_t>(pQueue));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkGetDeviceQueue,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, uint32_t queueFamilyIndex, uint32_t queueIndex, VkQueue* pQueue)>(g_original_fns["vkGetDeviceQueue"]);

    return original(device, queueFamilyIndex, queueIndex, pQueue);
}
// ---------------------------------------------------------------------------
// vkQueueSubmit
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkQueueSubmit_hook(VkQueue queue, uint32_t submitCount, const VkSubmitInfo* pSubmits, VkFence fence) {
    SPDLOG_TRACE("Intercepted: {}", "vkQueueSubmit");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(queue));
    ser.write_u32(static_cast<uint32_t>(submitCount));
    ser.write_array(pSubmits, submitCount);
    ser.write_handle(reinterpret_cast<uint64_t>(fence));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkQueueSubmit,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkQueue queue, uint32_t submitCount, const VkSubmitInfo* pSubmits, VkFence fence)>(g_original_fns["vkQueueSubmit"]);

    return original(queue, submitCount, pSubmits, fence);
}
// ---------------------------------------------------------------------------
// vkQueuePresentKHR
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkQueuePresentKHR_hook(VkQueue queue, const VkPresentInfoKHR* pPresentInfo) {
    SPDLOG_TRACE("Intercepted: {}", "vkQueuePresentKHR");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(queue));
    ser.write_raw(pPresentInfo, sizeof(*pPresentInfo));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkQueuePresentKHR,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkQueue queue, const VkPresentInfoKHR* pPresentInfo)>(g_original_fns["vkQueuePresentKHR"]);

    return original(queue, pPresentInfo);
}
// ---------------------------------------------------------------------------
// vkAllocateCommandBuffers
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkAllocateCommandBuffers_hook(VkDevice device, const VkCommandBufferAllocateInfo* pAllocateInfo, VkCommandBuffer* pCommandBuffers) {
    SPDLOG_TRACE("Intercepted: {}", "vkAllocateCommandBuffers");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pAllocateInfo, sizeof(*pAllocateInfo));
    ser.write_handle(reinterpret_cast<uint64_t>(pCommandBuffers));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkAllocateCommandBuffers,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkCommandBufferAllocateInfo* pAllocateInfo, VkCommandBuffer* pCommandBuffers)>(g_original_fns["vkAllocateCommandBuffers"]);

    return original(device, pAllocateInfo, pCommandBuffers);
}
// ---------------------------------------------------------------------------
// vkBeginCommandBuffer
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkBeginCommandBuffer_hook(VkCommandBuffer commandBuffer, const VkCommandBufferBeginInfo* pBeginInfo) {
    SPDLOG_TRACE("Intercepted: {}", "vkBeginCommandBuffer");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_raw(pBeginInfo, sizeof(*pBeginInfo));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkBeginCommandBuffer,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkCommandBuffer commandBuffer, const VkCommandBufferBeginInfo* pBeginInfo)>(g_original_fns["vkBeginCommandBuffer"]);

    return original(commandBuffer, pBeginInfo);
}
// ---------------------------------------------------------------------------
// vkEndCommandBuffer
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkEndCommandBuffer_hook(VkCommandBuffer commandBuffer) {
    SPDLOG_TRACE("Intercepted: {}", "vkEndCommandBuffer");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkEndCommandBuffer,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkCommandBuffer commandBuffer)>(g_original_fns["vkEndCommandBuffer"]);

    return original(commandBuffer);
}
// ---------------------------------------------------------------------------
// vkAllocateMemory
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkAllocateMemory_hook(VkDevice device, const VkMemoryAllocateInfo* pAllocateInfo, const VkAllocationCallbacks* pAllocator, VkDeviceMemory* pMemory) {
    SPDLOG_TRACE("Intercepted: {}", "vkAllocateMemory");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pAllocateInfo, sizeof(*pAllocateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pMemory));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkAllocateMemory,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkMemoryAllocateInfo* pAllocateInfo, const VkAllocationCallbacks* pAllocator, VkDeviceMemory* pMemory)>(g_original_fns["vkAllocateMemory"]);

    return original(device, pAllocateInfo, pAllocator, pMemory);
}
// ---------------------------------------------------------------------------
// vkFreeMemory
// ---------------------------------------------------------------------------
void VKAPI_PTR vkFreeMemory_hook(VkDevice device, VkDeviceMemory memory, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkFreeMemory");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(memory));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkFreeMemory,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkDeviceMemory memory, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkFreeMemory"]);

    return original(device, memory, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateBuffer
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateBuffer_hook(VkDevice device, const VkBufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkBuffer* pBuffer) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateBuffer");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pBuffer));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateBuffer,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkBufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkBuffer* pBuffer)>(g_original_fns["vkCreateBuffer"]);

    return original(device, pCreateInfo, pAllocator, pBuffer);
}
// ---------------------------------------------------------------------------
// vkDestroyBuffer
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyBuffer_hook(VkDevice device, VkBuffer buffer, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyBuffer");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(buffer));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyBuffer,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkBuffer buffer, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyBuffer"]);

    return original(device, buffer, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateImage
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateImage_hook(VkDevice device, const VkImageCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImage* pImage) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateImage");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pImage));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateImage,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkImageCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImage* pImage)>(g_original_fns["vkCreateImage"]);

    return original(device, pCreateInfo, pAllocator, pImage);
}
// ---------------------------------------------------------------------------
// vkDestroyImage
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyImage_hook(VkDevice device, VkImage image, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyImage");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(image));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyImage,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkImage image, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyImage"]);

    return original(device, image, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateImageView
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateImageView_hook(VkDevice device, const VkImageViewCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImageView* pView) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateImageView");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pView));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateImageView,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkImageViewCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImageView* pView)>(g_original_fns["vkCreateImageView"]);

    return original(device, pCreateInfo, pAllocator, pView);
}
// ---------------------------------------------------------------------------
// vkDestroyImageView
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyImageView_hook(VkDevice device, VkImageView imageView, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyImageView");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(imageView));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyImageView,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkImageView imageView, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyImageView"]);

    return original(device, imageView, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateShaderModule
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateShaderModule_hook(VkDevice device, const VkShaderModuleCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkShaderModule* pShaderModule) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateShaderModule");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pShaderModule));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateShaderModule,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkShaderModuleCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkShaderModule* pShaderModule)>(g_original_fns["vkCreateShaderModule"]);

    return original(device, pCreateInfo, pAllocator, pShaderModule);
}
// ---------------------------------------------------------------------------
// vkDestroyShaderModule
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyShaderModule_hook(VkDevice device, VkShaderModule shaderModule, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyShaderModule");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(shaderModule));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyShaderModule,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkShaderModule shaderModule, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyShaderModule"]);

    return original(device, shaderModule, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreatePipelineLayout
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreatePipelineLayout_hook(VkDevice device, const VkPipelineLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkPipelineLayout* pPipelineLayout) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreatePipelineLayout");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pPipelineLayout));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreatePipelineLayout,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkPipelineLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkPipelineLayout* pPipelineLayout)>(g_original_fns["vkCreatePipelineLayout"]);

    return original(device, pCreateInfo, pAllocator, pPipelineLayout);
}
// ---------------------------------------------------------------------------
// vkDestroyPipelineLayout
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyPipelineLayout_hook(VkDevice device, VkPipelineLayout pipelineLayout, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyPipelineLayout");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(pipelineLayout));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyPipelineLayout,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkPipelineLayout pipelineLayout, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyPipelineLayout"]);

    return original(device, pipelineLayout, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateGraphicsPipelines
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateGraphicsPipelines_hook(VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkGraphicsPipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateGraphicsPipelines");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(pipelineCache));
    ser.write_u32(static_cast<uint32_t>(createInfoCount));
    ser.write_array(pCreateInfos, createInfoCount);
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pPipelines));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateGraphicsPipelines,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkGraphicsPipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines)>(g_original_fns["vkCreateGraphicsPipelines"]);

    return original(device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines);
}
// ---------------------------------------------------------------------------
// vkCreateComputePipelines
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateComputePipelines_hook(VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkComputePipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateComputePipelines");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(pipelineCache));
    ser.write_u32(static_cast<uint32_t>(createInfoCount));
    ser.write_array(pCreateInfos, createInfoCount);
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pPipelines));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateComputePipelines,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkComputePipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines)>(g_original_fns["vkCreateComputePipelines"]);

    return original(device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines);
}
// ---------------------------------------------------------------------------
// vkDestroyPipeline
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyPipeline_hook(VkDevice device, VkPipeline pipeline, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyPipeline");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(pipeline));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyPipeline,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkPipeline pipeline, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyPipeline"]);

    return original(device, pipeline, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateRenderPass
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateRenderPass_hook(VkDevice device, const VkRenderPassCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkRenderPass* pRenderPass) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateRenderPass");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pRenderPass));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateRenderPass,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkRenderPassCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkRenderPass* pRenderPass)>(g_original_fns["vkCreateRenderPass"]);

    return original(device, pCreateInfo, pAllocator, pRenderPass);
}
// ---------------------------------------------------------------------------
// vkDestroyRenderPass
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyRenderPass_hook(VkDevice device, VkRenderPass renderPass, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyRenderPass");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(renderPass));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyRenderPass,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkRenderPass renderPass, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyRenderPass"]);

    return original(device, renderPass, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateFramebuffer
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateFramebuffer_hook(VkDevice device, const VkFramebufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFramebuffer* pFramebuffer) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateFramebuffer");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pFramebuffer));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateFramebuffer,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkFramebufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFramebuffer* pFramebuffer)>(g_original_fns["vkCreateFramebuffer"]);

    return original(device, pCreateInfo, pAllocator, pFramebuffer);
}
// ---------------------------------------------------------------------------
// vkDestroyFramebuffer
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyFramebuffer_hook(VkDevice device, VkFramebuffer framebuffer, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyFramebuffer");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(framebuffer));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyFramebuffer,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkFramebuffer framebuffer, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyFramebuffer"]);

    return original(device, framebuffer, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateDescriptorSetLayout
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateDescriptorSetLayout_hook(VkDevice device, const VkDescriptorSetLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorSetLayout* pSetLayout) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateDescriptorSetLayout");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pSetLayout));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateDescriptorSetLayout,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkDescriptorSetLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorSetLayout* pSetLayout)>(g_original_fns["vkCreateDescriptorSetLayout"]);

    return original(device, pCreateInfo, pAllocator, pSetLayout);
}
// ---------------------------------------------------------------------------
// vkDestroyDescriptorSetLayout
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyDescriptorSetLayout_hook(VkDevice device, VkDescriptorSetLayout descriptorSetLayout, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyDescriptorSetLayout");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(descriptorSetLayout));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyDescriptorSetLayout,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkDescriptorSetLayout descriptorSetLayout, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyDescriptorSetLayout"]);

    return original(device, descriptorSetLayout, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateDescriptorPool
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateDescriptorPool_hook(VkDevice device, const VkDescriptorPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorPool* pDescriptorPool) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateDescriptorPool");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pDescriptorPool));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateDescriptorPool,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkDescriptorPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorPool* pDescriptorPool)>(g_original_fns["vkCreateDescriptorPool"]);

    return original(device, pCreateInfo, pAllocator, pDescriptorPool);
}
// ---------------------------------------------------------------------------
// vkDestroyDescriptorPool
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyDescriptorPool_hook(VkDevice device, VkDescriptorPool descriptorPool, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyDescriptorPool");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(descriptorPool));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyDescriptorPool,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkDescriptorPool descriptorPool, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyDescriptorPool"]);

    return original(device, descriptorPool, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateFence
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateFence_hook(VkDevice device, const VkFenceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFence* pFence) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateFence");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pFence));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateFence,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkFenceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFence* pFence)>(g_original_fns["vkCreateFence"]);

    return original(device, pCreateInfo, pAllocator, pFence);
}
// ---------------------------------------------------------------------------
// vkDestroyFence
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroyFence_hook(VkDevice device, VkFence fence, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroyFence");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(fence));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroyFence,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkFence fence, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroyFence"]);

    return original(device, fence, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCreateSemaphore
// ---------------------------------------------------------------------------
VkResult VKAPI_PTR vkCreateSemaphore_hook(VkDevice device, const VkSemaphoreCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSemaphore* pSemaphore) {
    SPDLOG_TRACE("Intercepted: {}", "vkCreateSemaphore");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_raw(pCreateInfo, sizeof(*pCreateInfo));
    ser.write_raw(pAllocator, sizeof(*pAllocator));
    ser.write_handle(reinterpret_cast<uint64_t>(pSemaphore));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCreateSemaphore,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<VkResult (VKAPI_PTR*)(VkDevice device, const VkSemaphoreCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSemaphore* pSemaphore)>(g_original_fns["vkCreateSemaphore"]);

    return original(device, pCreateInfo, pAllocator, pSemaphore);
}
// ---------------------------------------------------------------------------
// vkDestroySemaphore
// ---------------------------------------------------------------------------
void VKAPI_PTR vkDestroySemaphore_hook(VkDevice device, VkSemaphore semaphore, const VkAllocationCallbacks* pAllocator) {
    SPDLOG_TRACE("Intercepted: {}", "vkDestroySemaphore");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_handle(reinterpret_cast<uint64_t>(semaphore));
    ser.write_raw(pAllocator, sizeof(*pAllocator));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkDestroySemaphore,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, VkSemaphore semaphore, const VkAllocationCallbacks* pAllocator)>(g_original_fns["vkDestroySemaphore"]);

    return original(device, semaphore, pAllocator);
}
// ---------------------------------------------------------------------------
// vkCmdDraw
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdDraw_hook(VkCommandBuffer commandBuffer, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdDraw");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_u32(static_cast<uint32_t>(vertexCount));
    ser.write_u32(static_cast<uint32_t>(instanceCount));
    ser.write_u32(static_cast<uint32_t>(firstVertex));
    ser.write_u32(static_cast<uint32_t>(firstInstance));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdDraw,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance)>(g_original_fns["vkCmdDraw"]);

    return original(commandBuffer, vertexCount, instanceCount, firstVertex, firstInstance);
}
// ---------------------------------------------------------------------------
// vkCmdDrawIndexed
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdDrawIndexed_hook(VkCommandBuffer commandBuffer, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t vertexOffset, uint32_t firstInstance) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdDrawIndexed");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_u32(static_cast<uint32_t>(indexCount));
    ser.write_u32(static_cast<uint32_t>(instanceCount));
    ser.write_u32(static_cast<uint32_t>(firstIndex));
    ser.write_u32(static_cast<uint32_t>(vertexOffset));
    ser.write_u32(static_cast<uint32_t>(firstInstance));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdDrawIndexed,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t vertexOffset, uint32_t firstInstance)>(g_original_fns["vkCmdDrawIndexed"]);

    return original(commandBuffer, indexCount, instanceCount, firstIndex, vertexOffset, firstInstance);
}
// ---------------------------------------------------------------------------
// vkCmdDispatch
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdDispatch_hook(VkCommandBuffer commandBuffer, uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdDispatch");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_u32(static_cast<uint32_t>(groupCountX));
    ser.write_u32(static_cast<uint32_t>(groupCountY));
    ser.write_u32(static_cast<uint32_t>(groupCountZ));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdDispatch,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ)>(g_original_fns["vkCmdDispatch"]);

    return original(commandBuffer, groupCountX, groupCountY, groupCountZ);
}
// ---------------------------------------------------------------------------
// vkCmdBindPipeline
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdBindPipeline_hook(VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipeline pipeline) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdBindPipeline");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_u32(static_cast<uint32_t>(pipelineBindPoint));
    ser.write_handle(reinterpret_cast<uint64_t>(pipeline));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdBindPipeline,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipeline pipeline)>(g_original_fns["vkCmdBindPipeline"]);

    return original(commandBuffer, pipelineBindPoint, pipeline);
}
// ---------------------------------------------------------------------------
// vkCmdSetViewport
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdSetViewport_hook(VkCommandBuffer commandBuffer, uint32_t firstViewport, uint32_t viewportCount, const VkViewport* pViewports) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdSetViewport");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_u32(static_cast<uint32_t>(firstViewport));
    ser.write_u32(static_cast<uint32_t>(viewportCount));
    ser.write_array(pViewports, viewportCount);

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdSetViewport,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, uint32_t firstViewport, uint32_t viewportCount, const VkViewport* pViewports)>(g_original_fns["vkCmdSetViewport"]);

    return original(commandBuffer, firstViewport, viewportCount, pViewports);
}
// ---------------------------------------------------------------------------
// vkCmdSetScissor
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdSetScissor_hook(VkCommandBuffer commandBuffer, uint32_t firstScissor, uint32_t scissorCount, const VkRect2D* pScissors) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdSetScissor");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_u32(static_cast<uint32_t>(firstScissor));
    ser.write_u32(static_cast<uint32_t>(scissorCount));
    ser.write_array(pScissors, scissorCount);

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdSetScissor,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, uint32_t firstScissor, uint32_t scissorCount, const VkRect2D* pScissors)>(g_original_fns["vkCmdSetScissor"]);

    return original(commandBuffer, firstScissor, scissorCount, pScissors);
}
// ---------------------------------------------------------------------------
// vkCmdPushConstants
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdPushConstants_hook(VkCommandBuffer commandBuffer, VkPipelineLayout layout, VkShaderStageFlags stageFlags, uint32_t offset, uint32_t size, const void* pValues) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdPushConstants");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_handle(reinterpret_cast<uint64_t>(layout));
    ser.write_u32(static_cast<uint32_t>(stageFlags));
    ser.write_u32(static_cast<uint32_t>(offset));
    ser.write_u32(static_cast<uint32_t>(size));
    ser.write_raw(pValues, size);

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdPushConstants,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, VkPipelineLayout layout, VkShaderStageFlags stageFlags, uint32_t offset, uint32_t size, const void* pValues)>(g_original_fns["vkCmdPushConstants"]);

    return original(commandBuffer, layout, stageFlags, offset, size, pValues);
}
// ---------------------------------------------------------------------------
// vkCmdBeginRenderPass
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdBeginRenderPass_hook(VkCommandBuffer commandBuffer, const VkRenderPassBeginInfo* pRenderPassBegin, VkSubpassContents contents) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdBeginRenderPass");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_raw(pRenderPassBegin, sizeof(*pRenderPassBegin));
    ser.write_u32(static_cast<uint32_t>(contents));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdBeginRenderPass,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, const VkRenderPassBeginInfo* pRenderPassBegin, VkSubpassContents contents)>(g_original_fns["vkCmdBeginRenderPass"]);

    return original(commandBuffer, pRenderPassBegin, contents);
}
// ---------------------------------------------------------------------------
// vkCmdEndRenderPass
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdEndRenderPass_hook(VkCommandBuffer commandBuffer) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdEndRenderPass");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdEndRenderPass,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer)>(g_original_fns["vkCmdEndRenderPass"]);

    return original(commandBuffer);
}
// ---------------------------------------------------------------------------
// vkCmdCopyBuffer
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdCopyBuffer_hook(VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkBuffer dstBuffer, uint32_t regionCount, const VkBufferCopy* pRegions) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdCopyBuffer");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_handle(reinterpret_cast<uint64_t>(srcBuffer));
    ser.write_handle(reinterpret_cast<uint64_t>(dstBuffer));
    ser.write_u32(static_cast<uint32_t>(regionCount));
    ser.write_array(pRegions, regionCount);

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdCopyBuffer,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkBuffer dstBuffer, uint32_t regionCount, const VkBufferCopy* pRegions)>(g_original_fns["vkCmdCopyBuffer"]);

    return original(commandBuffer, srcBuffer, dstBuffer, regionCount, pRegions);
}
// ---------------------------------------------------------------------------
// vkCmdPipelineBarrier
// ---------------------------------------------------------------------------
void VKAPI_PTR vkCmdPipelineBarrier_hook(VkCommandBuffer commandBuffer, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, VkDependencyFlags dependencyFlags, uint32_t memoryBarrierCount, const VkMemoryBarrier* pMemoryBarriers, uint32_t bufferMemoryBarrierCount, const VkBufferMemoryBarrier* pBufferMemoryBarriers, uint32_t imageMemoryBarrierCount, const VkImageMemoryBarrier* pImageMemoryBarriers) {
    SPDLOG_TRACE("Intercepted: {}", "vkCmdPipelineBarrier");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(commandBuffer));
    ser.write_u32(static_cast<uint32_t>(srcStageMask));
    ser.write_u32(static_cast<uint32_t>(dstStageMask));
    ser.write_u32(static_cast<uint32_t>(dependencyFlags));
    ser.write_u32(static_cast<uint32_t>(memoryBarrierCount));
    ser.write_array(pMemoryBarriers, memoryBarrierCount);
    ser.write_u32(static_cast<uint32_t>(bufferMemoryBarrierCount));
    ser.write_array(pBufferMemoryBarriers, bufferMemoryBarrierCount);
    ser.write_u32(static_cast<uint32_t>(imageMemoryBarrierCount));
    ser.write_array(pImageMemoryBarriers, imageMemoryBarrierCount);

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkCmdPipelineBarrier,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkCommandBuffer commandBuffer, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, VkDependencyFlags dependencyFlags, uint32_t memoryBarrierCount, const VkMemoryBarrier* pMemoryBarriers, uint32_t bufferMemoryBarrierCount, const VkBufferMemoryBarrier* pBufferMemoryBarriers, uint32_t imageMemoryBarrierCount, const VkImageMemoryBarrier* pImageMemoryBarriers)>(g_original_fns["vkCmdPipelineBarrier"]);

    return original(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers);
}
// ---------------------------------------------------------------------------
// vkUpdateDescriptorSets
// ---------------------------------------------------------------------------
void VKAPI_PTR vkUpdateDescriptorSets_hook(VkDevice device, uint32_t descriptorWriteCount, const VkWriteDescriptorSet* pDescriptorWrites, uint32_t descriptorCopyCount, const VkCopyDescriptorSet* pDescriptorCopies) {
    SPDLOG_TRACE("Intercepted: {}", "vkUpdateDescriptorSets");

    // Serialize arguments
    serializer::VulkanSerializer ser;
    ser.write_handle(reinterpret_cast<uint64_t>(device));
    ser.write_u32(static_cast<uint32_t>(descriptorWriteCount));
    ser.write_array(pDescriptorWrites, descriptorWriteCount);
    ser.write_u32(static_cast<uint32_t>(descriptorCopyCount));
    ser.write_array(pDescriptorCopies, descriptorCopyCount);

    // Append to batch
    if (g_batch) {
        auto builder = protocol::build_command(
            fbs::FunctionId_vkUpdateDescriptorSets,
            next_request_id(),
            ser.data(),
            ser.size()
        );
        g_batch->append(builder);
    }

    // Call original
    auto original = reinterpret_cast<void (VKAPI_PTR*)(VkDevice device, uint32_t descriptorWriteCount, const VkWriteDescriptorSet* pDescriptorWrites, uint32_t descriptorCopyCount, const VkCopyDescriptorSet* pDescriptorCopies)>(g_original_fns["vkUpdateDescriptorSets"]);

    return original(device, descriptorWriteCount, pDescriptorWrites, descriptorCopyCount, pDescriptorCopies);
}

// ---------------------------------------------------------------------------
// Initialization
// ---------------------------------------------------------------------------
void initialize_hooks() {
    if (g_initialized) return;

    SPDLOG_INFO("OmniGPU intercept initializing...");

    // TODO: populate g_original_fns with vkGetInstanceProcAddr / vkGetDeviceProcAddr
    // hook vkCreateInstance
    // hook vkDestroyInstance
    // hook vkEnumeratePhysicalDevices
    // hook vkCreateDevice
    // hook vkDestroyDevice
    // hook vkGetDeviceQueue
    // hook vkQueueSubmit
    // hook vkQueuePresentKHR
    // hook vkAllocateCommandBuffers
    // hook vkBeginCommandBuffer
    // hook vkEndCommandBuffer
    // hook vkAllocateMemory
    // hook vkFreeMemory
    // hook vkCreateBuffer
    // hook vkDestroyBuffer
    // hook vkCreateImage
    // hook vkDestroyImage
    // hook vkCreateImageView
    // hook vkDestroyImageView
    // hook vkCreateShaderModule
    // hook vkDestroyShaderModule
    // hook vkCreatePipelineLayout
    // hook vkDestroyPipelineLayout
    // hook vkCreateGraphicsPipelines
    // hook vkCreateComputePipelines
    // hook vkDestroyPipeline
    // hook vkCreateRenderPass
    // hook vkDestroyRenderPass
    // hook vkCreateFramebuffer
    // hook vkDestroyFramebuffer
    // hook vkCreateDescriptorSetLayout
    // hook vkDestroyDescriptorSetLayout
    // hook vkCreateDescriptorPool
    // hook vkDestroyDescriptorPool
    // hook vkCreateFence
    // hook vkDestroyFence
    // hook vkCreateSemaphore
    // hook vkDestroySemaphore
    // hook vkCmdDraw
    // hook vkCmdDrawIndexed
    // hook vkCmdDispatch
    // hook vkCmdBindPipeline
    // hook vkCmdSetViewport
    // hook vkCmdSetScissor
    // hook vkCmdPushConstants
    // hook vkCmdBeginRenderPass
    // hook vkCmdEndRenderPass
    // hook vkCmdCopyBuffer
    // hook vkCmdPipelineBarrier
    // hook vkUpdateDescriptorSets

    g_initialized = true;
    SPDLOG_INFO("OmniGPU intercept initialized ({} functions hooked)", 50);
}

void set_batch(batch::CommandBatch* batch) {
    g_batch = batch;
    SPDLOG_INFO("OmniGPU batch set ({} commands threshold)",
                batch ? batch->command_count() : 0);
}

void shutdown_hooks() {
    if (!g_initialized) return;
    g_batch = nullptr;
    g_original_fns.clear();
    g_initialized = false;
    SPDLOG_INFO("OmniGPU intercept shut down");
}

} // namespace omnigpu::intercept